CC = clang
CFLAGS = -std=gnu11

objects = Semaphore_Before Semaphore_After

all: $(objects)

Semaphore_Before:
Semaphore_Before.o:

Semaphore_After:
Semaphore_After.o:

.PHONY: clean
clean:
	-rm $(objects) *.o
